# Generated by Django 3.1.4 on 2020-12-17 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('n_matricule', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('civilite', models.CharField(choices=[('0', 'Monsieur'), ('1', 'Madame'), ('2', 'Mademoiselle')], max_length=1, verbose_name='Civilité')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=300, verbose_name='Prénoms')),
                ('nom_jeune_fille', models.CharField(max_length=400, null=True, verbose_name='Nom de jeune fille')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('sexe', models.CharField(choices=[('0', 'Homme'), ('1', 'Femme')], max_length=1, verbose_name='Sexe')),
                ('domicile', models.CharField(max_length=200, verbose_name='Domicile')),
                ('n_cnps', models.CharField(max_length=200, verbose_name='Numéro CNPS')),
                ('telephone_fixe', models.CharField(max_length=10, verbose_name='Téléphone fixe')),
                ('telephone_portable', models.CharField(max_length=10, verbose_name='Téléphone portable')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('situation_matri', models.CharField(choices=[('0', 'Marié(e)'), ('1', 'Célibataire'), ('2', 'Voeuf(e)'), ('3', 'Divorcé(e)')], max_length=1, verbose_name='Situation matrimoniale')),
                ('pointure_chauss', models.PositiveIntegerField(verbose_name='Pointure de chaussure')),
                ('date_entree', models.DateField(verbose_name="Date d'entrée")),
                ('date_depart', models.DateField(verbose_name='Date de départ')),
                ('nom_urgence', models.CharField(max_length=300, verbose_name="Nom de la personne à contacter en cas d'urgence")),
                ('contact_urgence', models.CharField(max_length=10, verbose_name="Contact de la personne à contacter en cas d'urgence")),
                ('dernier_emploi_exerce', models.CharField(max_length=100, verbose_name='Dernier emploi exercé')),
                ('precedent_employeur', models.CharField(max_length=100, verbose_name='Précédent employeur')),
                ('img_cv', models.FileField(null=True, upload_to='', verbose_name='CV')),
                ('img_dernier_diplome', models.FileField(null=True, upload_to='', verbose_name='Dernier diplôme obtenu')),
                ('img_extrait_naiss', models.FileField(null=True, upload_to='', verbose_name='Extrait de naissance')),
                ('img_ident', models.ImageField(null=True, upload_to='', verbose_name="Photo d'identité")),
                ('img_immat', models.ImageField(null=True, upload_to='', verbose_name="Photo de l'immatriculation CNPS")),
                ('img_carte_ident_pass', models.ImageField(null=True, upload_to='', verbose_name="Photo de la carte d'identité ou du passeport")),
            ],
            options={
                'verbose_name': 'Agent',
            },
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=300, verbose_name='Prénoms')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('sexe', models.CharField(choices=[('0', 'Homme'), ('1', 'Femme')], max_length=1, verbose_name='Sexe')),
                ('niveau_sc', models.CharField(max_length=100, verbose_name='Niveau scolaire')),
                ('img_extrait_naiss', models.FileField(null=True, upload_to='', verbose_name='Extrait de naissance')),
                ('img_ident', models.ImageField(null=True, upload_to='', verbose_name="Photo d'identité")),
                ('etat_sante', models.CharField(max_length=200, verbose_name='Etat de santé')),
            ],
            options={
                'verbose_name': 'Enfant',
            },
        ),
        migrations.CreateModel(
            name='Frere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=300, verbose_name='Prénoms')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('etat_sante', models.CharField(max_length=200, verbose_name='Etat de santé')),
            ],
            options={
                'verbose_name': 'Frère',
            },
        ),
        migrations.CreateModel(
            name='Mere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=300, verbose_name='Prénoms')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('etat_sante', models.CharField(max_length=200, verbose_name='Etat de santé')),
            ],
            options={
                'verbose_name': 'Mère',
            },
        ),
        migrations.CreateModel(
            name='Pere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=300, verbose_name='Prénoms')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('etat_sante', models.CharField(max_length=200, verbose_name='Etat de santé')),
            ],
            options={
                'verbose_name': 'Père',
            },
        ),
        migrations.CreateModel(
            name='Qualif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.CharField(max_length=500, verbose_name='Diplôme')),
                ('etabl', models.CharField(max_length=500, verbose_name='Etablissement')),
                ('annee', models.CharField(max_length=9, verbose_name='Année')),
            ],
            options={
                'verbose_name': 'Qualification',
            },
        ),
        migrations.CreateModel(
            name='Soeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=300, verbose_name='Prénoms')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('etat_sante', models.CharField(max_length=200, verbose_name='Etat de santé')),
            ],
            options={
                'verbose_name': 'Soeur',
            },
        ),
        migrations.CreateModel(
            name='Passeport',
            fields=[
                ('n_passeport', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Numéro du passeport ')),
                ('lieu_del', models.CharField(max_length=200, verbose_name='Lieu de délivrance')),
                ('date_del', models.DateField(verbose_name='Date de délivrance')),
                ('date_exp', models.DateField(verbose_name="Date d'expiration'")),
                ('nationalite', models.CharField(max_length=200, verbose_name='Nationalité')),
                ('sec_nationalite', models.CharField(max_length=200, verbose_name='Seconde nationalité')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.agent')),
            ],
            options={
                'verbose_name': 'Passeport',
            },
        ),
        migrations.CreateModel(
            name='Details_banc',
            fields=[
                ('n_compte', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Numéro de compte')),
                ('nom_etabl', models.CharField(max_length=500, verbose_name="Nom de l'établissement")),
                ('adresse', models.CharField(max_length=200, verbose_name='Adresse')),
                ('telephone', models.CharField(max_length=10, verbose_name='Téléphone')),
                ('code_iban', models.CharField(max_length=200, verbose_name='CODE IBAN')),
                ('code_swift', models.CharField(max_length=200, verbose_name='CODE SWIFT')),
                ('img_rib', models.ImageField(null=True, upload_to='', verbose_name='Photo RIB')),
                ('img_releve_banc', models.ImageField(null=True, upload_to='', verbose_name='Photo rélévé bancaire')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.agent')),
            ],
            options={
                'verbose_name': 'Détails bancaires',
            },
        ),
        migrations.CreateModel(
            name='Conjoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=300, verbose_name='Prénoms')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('telephone_portable', models.CharField(max_length=10, verbose_name='Téléphone portable')),
                ('img_extrait_naiss', models.FileField(null=True, upload_to='', verbose_name='Extrait de naissance')),
                ('img_ident', models.ImageField(null=True, upload_to='', verbose_name="Photo d'identité")),
                ('etat_sante', models.CharField(max_length=200, null=True, verbose_name='Etat de santé')),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.agent')),
            ],
            options={
                'verbose_name': 'Conjoint',
            },
        ),
        migrations.CreateModel(
            name='Carte_ident',
            fields=[
                ('n_carte_ident', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name="Numéro de la carte d'identité ")),
                ('lieu_del', models.CharField(max_length=200, verbose_name='Lieu de délivrance')),
                ('date_del', models.DateField(verbose_name='Date de délivrance')),
                ('date_exp', models.DateField(verbose_name="Date d'expiration'")),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.agent')),
            ],
            options={
                'verbose_name': "Carte d'identité",
            },
        ),
        migrations.CreateModel(
            name='Ant_sante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosp_chir', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Avez-vous déjà été hospitalisé(e) pour opération chirugicale ?')),
                ('hosp_acc', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Avez-vous déjà été hospitalisé(e) pour accident ?')),
                ('hosp_rep', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Avez-vous déjà été hospitalisé(e) pour cure de repos ?')),
                ('hosp_mal', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Avez-vous déjà été hospitalisé(e) pour maladie ?')),
                ('pre_1', models.CharField(max_length=300, null=True, verbose_name='Si oui, précisez ?')),
                ('att_ecz', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name="Avez-vous été ou êtes-vous atteint(e) de problème d'eczéma aux mains ?")),
                ('att_all', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name="Avez-vous été ou êtes-vous atteint(e) d'allergie, eczéma(autre), rhume des foins ?")),
                ('att_resp', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Avez-vous été ou êtes-vous atteint(e) de problèmes respiratoires (asthme, bronchite, emphysème, tuberculose) ?')),
                ('att_con', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Avez-vous été ou êtes-vous atteint(e) de perte de connaissance ?')),
                ('att_cer', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Avez-vous été ou êtes-vous atteint(e) de commotion cérébrale ?')),
                ('att_conv', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name="Avez-vous été ou êtes-vous atteint(e) d'épilepsie ? Convulsions ?")),
                ('att_depr', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Avez-vous été ou êtes-vous atteint(e) de dépression nerveuse ? Epuisement ?')),
                ('att_stress', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Avez-vous été ou êtes-vous atteint(e) du stress ? Burn-out ?')),
                ('att_peur', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Avez-vous été ou êtes-vous atteint(e) de la peur du vide ou du travail en hauteur ?')),
                ('att_diab', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Avez-vous été ou êtes-vous atteint(e) du diabète ?')),
                ('att_diges', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Avez-vous été ou êtes-vous atteint(e) de maladie digestive ?')),
                ('att_her', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name="Avez-vous été ou êtes-vous atteint(e) d' hernie ?")),
                ('att_art', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name="Avez-vous été ou êtes-vous atteint(e) d' hypertension artérielle ?")),
                ('att_coeur', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Avez-vous été ou êtes-vous atteint(e) de maladie du coeur ?')),
                ('att_vein', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Avez-vous été ou êtes-vous atteint(e) de maladie des artères, des veines ?')),
                ('att_or', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Avez-vous été ou êtes-vous atteint(e) de maladie des oreilles, du nez, des sinus ?')),
                ('att_ves', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name="Avez-vous été ou êtes-vous atteint(e) de vestiges, perte de l'équilibre ?")),
                ('att_sg', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Avez-vous été ou êtes-vous atteint(e) de maladie du sang ?')),
                ('att_dos', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Avez-vous été ou êtes-vous atteint(e) de maux de dos, rhumatismes ?')),
                ('att_mus', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Avez-vous été ou êtes-vous atteint(e) de tendinites, problèmes articulaires, musculaires ?')),
                ('sub_car', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Avez-vous précédemment subi un éléctrocardiogramme ?')),
                ('sub_enc', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Avez-vous précédemment subi un éléctroencéphalogramme ?')),
                ('trait_med', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Avez-vous précédemment été traité(e) par des médicaments pendant une longue période ?')),
                ('pre_2', models.CharField(max_length=300, null=True, verbose_name='Si oui, précisez ?')),
                ('prat', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Pratiquez-vous régulièrement une ou plusieurs activités physiques ?')),
                ('pre_3', models.CharField(max_length=300, verbose_name='Si oui le(s) quel(s) ?')),
                ('cons_al', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name="Consommez-vous régulièrement de l'alcool, du vin, de la bière ?")),
                ('cons_tab', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Consommez-vous régulièrement du tabac ?')),
                ('cons_med', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Consommez-vous régulièrement des médicaments ?')),
                ('pre_4', models.CharField(max_length=300, null=True, verbose_name='Si oui, lesquels ?')),
                ('cons_drog', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Consommez-vous régulièrement des drogues, stupéfiants ?')),
                ('pre_5', models.CharField(max_length=300, null=True, verbose_name='Si oui, lesquels ?')),
                ('inv', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Une ou des invalidités ou incapacités permanentes vous sont-elles reconnues ?')),
                ('pre_6', models.CharField(max_length=300, null=True, verbose_name='Si oui, quels en sont les taux ?')),
                ('vac_tet', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Etes-vous vacciné contre le tétanos ?')),
                ('vac_ha', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name="Etes-vous vacciné contre l'hépatite A ?")),
                ('vac_hb', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name="Etes-vous vacciné contre l'hépatite B ?")),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.agent')),
            ],
            options={
                'verbose_name': 'Antécédents de santé',
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='enfants',
            field=models.ManyToManyField(blank=True, related_name='agents', to='home.Enfant'),
        ),
        migrations.AddField(
            model_name='agent',
            name='freres',
            field=models.ManyToManyField(blank=True, related_name='agents', to='home.Frere'),
        ),
        migrations.AddField(
            model_name='agent',
            name='mere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mere'),
        ),
        migrations.AddField(
            model_name='agent',
            name='pere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pere'),
        ),
        migrations.AddField(
            model_name='agent',
            name='qualifications',
            field=models.ManyToManyField(blank=True, related_name='agents', to='home.Qualif'),
        ),
        migrations.AddField(
            model_name='agent',
            name='soeurs',
            field=models.ManyToManyField(blank=True, related_name='agents', to='home.Soeur'),
        ),
    ]
